<a href="https://colab.research.google.com/github/RiriLumin22/Linear-Algebra-58019/blob/main/Coding_Activity_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**ACTIVITY 3**##

In [1]:
import numpy as np
A = np.array([[4,10,8],[10,26,26],[8,26,61]]) #creation of matrix A
print(A)
print()
inv_A = np.linalg.inv(A) #creation of inverse matrix A
print(inv_A)

[[ 4 10  8]
 [10 26 26]
 [ 8 26 61]]

[[ 25.27777778 -11.16666667   1.44444444]
 [-11.16666667   5.          -0.66666667]
 [  1.44444444  -0.66666667   0.11111111]]


In [2]:
import numpy as np
B= np.array([[44],[128],[214]]) #creation of matrix B
print(B)

[[ 44]
 [128]
 [214]]


In [3]:
X = np.dot(inv_A,B)
print(X)

[[-8.]
 [ 6.]
 [ 2.]]


##**To check if the answer is correct**##

In [5]:
Z = np.dot(A,X) 
print(Z)

[[ 44.]
 [128.]
 [214.]]
