<a href="https://colab.research.google.com/github/RiriLumin22/Linear-Algebra-58019/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Final Exam**#

##Problem 1##

In [16]:
eq1=np.array([[1,1,1],[1,0,4],[0,0,5]])
eq2=np.array([[89],[89],[95]])
amt=np.linalg.inv(eq1).dot(eq2)
print(amt)

[[13.]
 [57.]
 [19.]]


##Problem 2##

In [22]:
import numpy as np
from scipy.linalg import solve
A=np.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
print(A)
print()
B=np.array([[5],[15],[-20]])
print(B)
print()

#ERROR
#X= solve(A,B)
#print(X)

print('ERROR: LinAlgError: Singular Matrix')
print('This problem 2 results in an error since the determinant is 0. Thus, the inverse of the matrix does not exist.')

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]

[[  5]
 [ 15]
 [-20]]

ERROR: LinAlgError: Singular Matrix
This problem 2 results in an error since the determinant is 0. Thus, the inverse of the matrix does not exist.


##Problem 3##

In [7]:
import numpy as np
from numpy.linalg import eig

A = np.array([[8, 5, -6],[-12, -9, 12],[-3, -3, 5]])
print(A)
print()
w,v = np.linalg.eig(A)
print("The Eigenvalues are:\n",w)
print()
print("The Eigenvectors are:\n",v.round())

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]

The Eigenvalues are:
 [-1.  3.  2.]

The Eigenvectors are:
 [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
