<a href="https://colab.research.google.com/github/RiriLumin22/Linear-Algebra-58019/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##MIDTERM EXAM##

##**QUESTION 1**##

In [2]:
import numpy as np

SM = np.array ([[1,2,3,4,5],[2,0,0,0,0],[3,0,0,0,0],[4,0,0,0,0],[5,0,0,0,0]]) #5x5 matrix
print(SM) #displays a square matrix whose length is 5

[[1 2 3 4 5]
 [2 0 0 0 0]
 [3 0 0 0 0]
 [4 0 0 0 0]
 [5 0 0 0 0]]


##**QUESTION 2**##

In [11]:
import numpy as np
A = np.array ([[1,1,1,1,],[0,1,1,1,],[0,0,1,1,],[0,0,0,1],]) 
print()
print(A)


[[1 1 1 1]
 [0 1 1 1]
 [0 0 1 1]
 [0 0 0 1]]


##**QUESTION 3**##

In [15]:
import numpy as np
C = np.array([[1,2,3,4,5],[2,1,2,3,4],[3,2,1,2,3],[4,3,2,1,2],[5,4,3,2,1]]) #create a symmetrical matrix
print(C)

[[1 2 3 4 5]
 [2 1 2 3 4]
 [3 2 1 2 3]
 [4 3 2 1 2]
 [5 4 3 2 1]]


##**QUESTION 4**##

In [3]:
import numpy as np

C = np.array ([[1,2,3],[2,3,3],[3,4,-2]])
print(C)
print()
inv_C = np.linalg.inv(C) #creation of inverse matrix C
print(inv_C) #displays inverse of matrix C

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


##**QUESTION 5**##

In [17]:
C = np.array ([[1,2,3], [2,3,3], [3,4,-2]]) #create Matrix C
print(C)
print()
print (round(np.linalg.det(C))) #determinant of given matrix C from Question 4

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]

5


##**QUESTION 6**##

In [18]:
A = np.array([[5,4,1], [10,9,4], [10,13,15]])

B = np.array([[[3.4], [8.8], [19.2]]])

C = np.linalg.inv(A) @ B #root of the equation

print(C)

[[[0.2]
  [0.4]
  [0.8]]]
