<a href="https://colab.research.google.com/github/RiriLumin22/Linear-Algebra-58019/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Practical Lab Exam 1**

**Problem 1.**

In [9]:
#Numpy

import numpy as np

A = np.array([[1,2,3],[4,5,6]])
print(A) ###Display A
print()
B = np.array([[1,2],[3,4],[5,6]])
print(B) ###Display B
print()
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(C) ###Display C
print()
D = np.array([[1,2],[3,4]])
print(D) ###Display D
print()

dot = np.dot(A,B)
print(dot) ###Display the dot product of A and B
print()
print(D+D) ###Display the sum of D+D
print()
print(2*C) ### C multiplied by 2

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2]
 [3 4]]

[[22 28]
 [49 64]]

[[2 4]
 [6 8]]

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


**Problem 2.**

In [12]:
import numpy as np
A = np.array([5,3,-1])

print ("Size of Array is:", A.size) ###Display the size of the array
print ("Type of Array is:", type(A)) ###Display the type of array
print ("Shape of Array is:", A.shape) ###Display the shape of array
print ("Dimension of Array is:", A.ndim) ###Display the dimension of array

Size of Array is: 3
Type of Array is: <class 'numpy.ndarray'>
Shape of Array is: (3,)
Dimension of Array is: 1
