<a href="https://colab.research.google.com/github/RiriLumin22/Linear-Algebra-58019/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Prelim Exam**##

#Matrix C#

In [ ]:
#Question1
#Numpy

import numpy as np
C = np.array([[1,4,4,4],[4,1,4,4],[4,4,1,4],[4,4,4,1]]) ## A 4x4 matrix which displays the diagonal elements are all one (1s)
print(C) ## Displays the result

[[1 4 4 4]
 [4 1 4 4]
 [4 4 1 4]
 [4 4 4 1]]


In [2]:
#Question2
#Numpy

import numpy as np
C = np.array([[1,4,4,4],[4,1,4,4],[4,4,1,4],[4,4,4,1]]) ## A 4x4 matrix which is related to question 1 and that the values are doubled
print(C) ## Display the result (diagonal elements are one (1s))
print()
print(C*2) ## Displays the result (Double the values)

[[1 4 4 4]
 [4 1 4 4]
 [4 4 1 4]
 [4 4 4 1]]

[[2 8 8 8]
 [8 2 8 8]
 [8 8 2 8]
 [8 8 8 2]]


In [ ]:
#Question3
#Numpy

import numpy as np
A = np.array([2,7,4]) 
B = np.array([3,9,8])

C = np.cross(A,B) ## Cross product of matrices A and B
print(C) ## Display the result

[20 -4 -3]
