<a href="https://colab.research.google.com/github/RiriLumin22/Linear-Algebra-58019/blob/main/PythonExercise1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix and its Operations

In [4]:
#Numpy
import numpy as np
a=np.array([[-5,0],[4,1]])
print(a)
print()
b=np.array([[6,-3],[2,3]])
print(b)
print()
print(a+b) #Sum=A+B
print()
print(b-a) #difference1=B-A
print()
print(a-b) #difference2=A-B

[[-5  0]
 [ 4  1]]

[[ 6 -3]
 [ 2  3]]

[[ 1 -3]
 [ 6  4]]

[[11 -3]
 [-2  2]]

[[-11   3]
 [  2  -2]]
