<a href="https://colab.research.google.com/github/RiriLumin22/Linear-Algebra-58019/blob/main/Vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#numpy
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
#numpy
import numpy as np
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
